[package]
name = "multicast-dns-utils"
version = "0.2.1"
authors = ["Aleh Zasypkin <azasypkin@mozilla.com>"]

[dependencies]
docopt = "0.7.0"
rustc-serialize = "0.3.22"
multicast_dns = { git = "https://github.com/fxbox/multicast-dns.git", branch = "master" }
