[package]
name = "multicast-dns-utils"
version = "0.2.0"
authors = ["Aleh Zasypkin <azasypkin@mozilla.com>"]

[dependencies]
docopt = "0.6.81"
docopt_macros = "0.6.84"
rustc-serialize = "0.3.19"
multicast_dns = { git = "https://github.com/fxbox/multicast-dns.git", rev = "91fe8d4" }
