[package]
name = "multicast-dns-utils"
version = "0.1.1"
authors = ["Aleh Zasypkin <azasypkin@mozilla.com>"]

[dependencies]
docopt = "0.6.80"
docopt_macros = "0.6.84"
rustc-serialize = "0.3.19"
multicast_dns = { git = "https://github.com/fxbox/multicast-dns.git", rev = "b390be4" }
